# The main entry point of workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
# taken from https://github.com/snakemake-workflows
import sys
include: "rules/Snakemake_C4.smk"
#include: "rules/common.smk"
#include: "rules/ref.smk"
#include: "rules/qc.smk"
#include: "rules/cutadapt.smk"
#include: "rules/mapping.smk"
#include: "rules/splicing.smk"
#include: "rules/quantification.smk"

# 20220719 commented out until QC steps added/needed
#rule all_qc_report:
#    input: all_input , "results/multiqc_report.html"

if not os.path.exists("00log"):
    os.makedirs("00log")
if not os.path.exists("logs_slurm"):
    os.makedirs("logs_slurm")
if not os.path.exists("results"):
    os.makedirs("results")
if not os.path.exists("results/coverage"):
    os.makedirs("results/coverage")


localrules: run_merge_gene_tpms, run_multiqc, run_merge_junctions_STAR
